### ISSUE TITLE
local gctl: auto set namespace selector against watch via some environment variable

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/metac#102]
**_Problem Statement_**: I would like to use Metac as a library that is packaged as my own binary. This binary will get deployed as a Kubernetes Deployment or STS. I would like to use MetaController CR as a config that should only consider watches in this Deployment/STS namespace.

**Comment by grzesuav** [comment]
@AmitKumarDas maybe could you elaborate what is needed to achieve this behavior ?

**Comment by AmitKumarDas** [comment]
I will try to explain via a sample config for GenericController.

NOTE: A config has schema that matches one or more GenericController(s). This config is typically placed at /etc/config/metac/ path of the container. This container hosts the metac binary that reads this config & starts informers _(one informer per watch mentioned in GenericController)_. 

NOTE: In my case this binary is a golang project that uses metac as a library

Following is a sample config that makes use of 2 GenericControllers. On the whole, we want the metac binary to start informers for watches _with kind CStorClusterPlan & CStorClusterStorageSet_
```yaml
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-plan
  namespace: cspauto
spec:
  # i would like to watch kind CStorClusterPlan created under namespace
  # that matches the namespace of the binary that has this config file
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
    updateStrategy:
      method: InPlace
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterplan
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-storageset
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterstorageset
```

Coming back to the problem statement, I would like to spin up multiple metac binaries in dedicated namespaces. I want each binary to lookup up the watches that belong to its own namespace & proceed with its reconciliation.

### Possible solution:
We can define following new environment variables e.g.:
- MATCH_WATCH_WITH_SELF_NAMESPACE: <true/false>
- SELF_NAMESPACE: _(this will be a K8s downward API that will hold the POD's namespace)_

Now when metac starts, the resulting GenericControllers will be like following:
```yaml
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-plan
  namespace: cspauto
spec:
  # i would like to watch kind CStorClusterPlan created under namespace
  # that matches the namespace of the binary that has this config file
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
    advancedSelector:
      selectorTerms:
      - matchFields:
          metadata.namespace: <POD's namesapce>
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
    updateStrategy:
      method: InPlace
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterplan
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-storageset
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
    advancedSelector:
      selectorTerms:
      - matchFields:
          metadata.namespace: <POD's namesapce>
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterstorageset
```


Above will need to work when metac binary is meant to be run by looking up its config file _(described above)_. In other words metac needs to be started with following args:
```yaml
 args:
        - --run-as-local
```
