### ISSUE TITLE
Metac - use case question

### ISSUE THREAD

**Issue by burningalchemist** [AmitKumarDas/metac#114]
Hi @AmitKumarDas,

Just a quick question, if you have time for it.
I'm trying to use metac/metacontroller so it could patch the existing object's specs (Service). It works with labels/annotations, but what I need is to inject an additional configuration parameter (in my case - `externalIPs`). The problem is that `metac` doesn't update the existing object (_not_ created by itself), but rather tries to create a new one, which already exists. I suspect, that although it seemed to be easy at first to use metac for that, it's a wrong tool and I have no other chance but to implement a custom `MutatingAdmissionWebhookController`. What's your opinion?

Kind regards,
Sergei

**Comment by AmitKumarDas** [comment]
Hi @burningalchemist ,
IMO `GenericController` from metac should solve your requirements. Did you try metac already? Can you provide the yamls to look into further?

I guess, in your specific case both watch & attachment are same. So watch & attachment resources can be configured to Service. One can further filter the attachment to refer to same watch via advanced filters. One need to be a bit careful to avoid getting into hot loops since updating the attachment will trigger reconciliation of watch, since both are same. However if fixed values are being updated (IPs in your case), this should be safe.

Getting back to the topic of MutatingWebHooks, I would prefer the one with low maintenance overhead. 

#### References
- You may want to have a look at https://github.com/AmitKumarDas/metac/tree/master/examples/gctl/uninstall-openebs where its able to _update as well as delete resources_ that were created by someone else.
- Refer UpdateAny & DeleteAny fields:  https://github.com/AmitKumarDas/metac/blob/master/examples/gctl/uninstall-openebs/config/config.yaml#L5-L11
- Further needs are being tracked under https://github.com/AmitKumarDas/metac/issues/89
- Advanced filters API: 
  - https://github.com/AmitKumarDas/metac/blob/master/apis/metacontroller/v1alpha1/types_generic.go#L176
  - https://github.com/AmitKumarDas/metac/blob/master/apis/metacontroller/v1alpha1/selector.go#L31
- Advanced filters example: https://github.com/mayadata-io/d-operators/blob/master/config/metac.yaml

**Comment by burningalchemist** [comment]
@AmitKumarDas Thank you for a quick response!

Yeah, I've implemented the whole stuff but with `DecoratorController` for the moment (I've come from Metacontroller implementation) and I bumped into that kind of issue.

I'm on the same page with you, `MutatingAdmissionWebhook` for such a small thing seems like an overkill. I'll try to provide more details if you don't mind, but I'll also look into what you've provided already. Thanks again! :)

**Comment by AmitKumarDas** [comment]
@burningalchemist you may try something like below:

```yaml
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  # namespace & name combination should be unique
  # across all the GenericControllers in this file
  name: sync-services
  namespace: my-namespace
spec:
  # set update any to true since these Services are created
  # by some other tools, workflows, etc
  updateAny: true
  # kind Service is watched
  watch:
    apiVersion: v1
    resource: services
    # you may want to add label or ann selector to filter the watches further
  attachments:
  - apiVersion: v1
    resource: services
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        # select the Service resource (i.e. attachment) that is same as Watch
        - key: metadata.uid
          operator: EqualsWatchUID
  hooks:
    sync:
    # fill in your details
```

**Comment by burningalchemist** [comment]
Hi @AmitKumarDas Thanks a lot for the snippet, I'll try it out as soon as I can and share the feedback. I had to shift my gears to something different this week, but will get back and let you know. :)

**Comment by burningalchemist** [comment]
@AmitKumarDas I have a related question, which I can't get so far.
This is the `config.yml` which gets loaded by GenericController:
```apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-services
  namespace: metallb-system
spec:
  # set update any to true since these Services are created
  # by some other tools, workflows, etc
  updateAny: true
  # kind Service is watched
  watch:
    apiVersion: v1
    resource: services
    annotationSelector:
      matchExpressions:
      - {key: metacontroller, operator: Exists}
  attachments:
  - apiVersion: v1
    resource: services
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        # select the Service (i.e. attachment) that is same as Watch
        - key: metadata.uid
          operator: EqualsWatchUID
  hooks:
    sync:
      inline:
        funcName: update/service
```
The logic is empty yet (took it from the example):
```go
func updateService(request *generic.SyncHookRequest, response *generic.SyncHookResponse) error {
	if response == nil {
		response = &generic.SyncHookResponse{}
	}

	if request.Attachments.IsEmpty() {
		response.Finalized = true
		return nil
	}

	for _, attachment := range request.Attachments.List() {
		if attachment.GetKind() == "Service" {
			println(attachment)
			response.Attachments = append(response.Attachments, attachment)
			continue
		}

	}

	return nil
}
```
I have only a single service which contains annotation `metacontroller: "true"` - nginx. So I expect it to be filtered among all the services. But actually I get more than a single service observed:
```
I0325 18:05:46.779493       1 controller.go:716] WatchGCtl metallb-system/sync-services: Will apply attachments: Observed Resource Instances:-
	Service.v1:nginx f4f80ba1-7313-4a46-82f5-e1d7fcbb8094
	Service.v1:speaker 2d1278d4-456d-45b5-bc89-e8c0a2260ec0
	Service.v1:kube-dns b13ab268-eeed-4c52-bc0d-1a7a50bf856d
	Service.v1:redis d4ac93a4-4f16-43f1-bd42-4fca81b8ad9d
: Desired Resource Instances:-
	Service.v1:nginx f4f80ba1-7313-4a46-82f5-e1d7fcbb8094
	Service.v1:speaker 2d1278d4-456d-45b5-bc89-e8c0a2260ec0
	Service.v1:kube-dns b13ab268-eeed-4c52-bc0d-1a7a50bf856d
	Service.v1:redis d4ac93a4-4f16-43f1-bd42-4fca81b8ad9d
```
Do I use AnnotationSelector incorrectly?

**Comment by AmitKumarDas** [comment]
@burningalchemist can you try this? 

You may probably want to try things in different environment other than production before applying the same in production. I really don't have any other idea, other than implementing a DryRun stuff etc _(a long term stuff)_.

I have removed one selector from attachments. This additional selector was a OR operation & hence multiple services were considered as attachments.

```yaml
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-services
  namespace: metallb-system
spec:
  # set update any to true since these Services are created
  # by some other tools, workflows, etc
  updateAny: true
  # kind Service is watched
  watch:
    apiVersion: v1
    resource: services
    annotationSelector:
      matchExpressions:
      - {key: metacontroller, operator: Exists}
  attachments:
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        # select the Service (i.e. attachment) that is same as Watch
        - key: metadata.uid
          operator: EqualsWatchUID
  hooks:
    sync:
      inline:
        funcName: update/service
```
