### ISSUE TITLE
usecase: Cron Controller similar to CronJob Controller.

### ISSUE THREAD

**Issue by rahulchheda** [AmitKumarDas/metac#135]
So there is a dire need of a controller that can help me do CRUD operations on some CR, but those operations must be following the CronTab, and have all other functionality supported in the cronJob Controller, such as Concurrency Policy, Delayed Retry Time, and others.

**Comment by rahulchheda** [comment]
cc: @AmitKumarDas

**Comment by AmitKumarDas** [comment]
@rahulchheda Can you please put some yamls to describe a little better. Do you have the specs of Cron controller in your mind already?

**Comment by rahulchheda** [comment]
So, what I have in mind would be a little vague, I think you would help me shape my thoughts a little bit also.
So, I want to have all functionality of v1beta1.CronJob (the spec will be the same as CronJob), but in template field, we would have namespaced-name of the a Custom Resource.
So the controller operations would be perform CRUD operation on that CR (which the template refer to) similar to that of CronJob, for example: create on schedule, delete the expired one, concurrency policy, and many other functions that CronJob has now.

**Comment by rahulchheda** [comment]
```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: rdm2bq
  labels:
    name: rdm2bq
    role: job
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: engine123
      namespace: jack
 ```
