### ISSUE TITLE
add granular update & delete options to GenericController

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/metac#89]
**_Problem Statement_**: A GenericController can create, update or delete any attachments. There are no visible issues if this controller deletes or updates the attachments which were created by this controller. However, one would like to exercise finer control via GenericController while trying to delete or update resources that were **not** created by the same controller. GenericController already supports `UpdateAny` & `DeleteAny` options which is common to all the attachments specified in its spec. However, this is too liberal and can create problems if not programmed properly. There are also other scenarios where one would like to only Update certain kind of attachments whereas Delete certain kind of attachments and at the same time do nothing for certain kind of attachments. All these scenarios calls for finer granularity while exercising these Update/Delete/Noop operations.

**_Possible Solution:_** One of the possible approaches can be to expose new tunables in GenericController's HookResponse API. This new tunables can be set by controller developers who write the reconcile logic. In other words, this will be controlled from inside the hook code & not by Metac. This also allows us to avoid setting generic tunables like `UpdateAny` & `DeleteAny` in the spec.

### sample hook response
```yaml
response: 
  allowedDeletes:
    # gvk: namespace/name
    # __ i.e. double underscore is the separator used
    # / i.e. forward slash can be used instead once verified if it works for all cases
    openebs.io__v1alpha1__Deployment: default/cool
  allowedUpdates:
    openebs.io__v1alpha1__Pod: default/nginx
```
```go
type GenericControllerWebHookResponse struct {
 // existing fields...

 // new fields
  allowedUpdates map[string]string
  allowedDeletes map[string]string
}
```

**Comment by AmitKumarDas** [comment]
It will be better to use `ObjectMeta` & `Type` fields to determine what is eligible to be updated &/ deleted. For example a sample response will be as follows:
```yaml
response: 
  allowedDeletes:
  - kind:
    apiVersion:
    name:
    namespace:
  allowedUpdates:
  - kind:
    apiVersion:
    name:
    namespace:
```

In addition, a few scenarios might want to expose those resources that are eligible to be sync-ed _(i.e. both update, delete)_. OTH the response structure can look like the following:
```yaml
response: 
  allowedSyncs:
  - kind:
    apiVersion:
    name:
    namespace:
  allowedDeletes:
  - kind:
    apiVersion:
    name:
    namespace:
  allowedUpdates:
  - kind:
    apiVersion:
    name:
    namespace:
```

**Comment by AmitKumarDas** [comment]
We might want to consider following cases:
- updates can be granted based on specified kind & apiVersion
- deletes can be granted based on specified kind, apiVersion, name & namespace

```yaml
response: 
  allowedDeletes:
  - kind:
    apiVersion:
    name:
    namespace:
  allowedUpdates:
  - kind:
    apiVersion:
```

NOTE: One might consider using wildcards i.e. '*' as well. For example:

```yaml
response: 
  allowedDeletes:
  - kind:
    apiVersion:
    name:
    namespace:
  allowedUpdates:
  - kind: *
    apiVersion: *
    namespace: * # * is the default value for namespace
    name: * # * is the default value for name
```
